# Generated by Django 2.2 on 2021-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=264),
            preserve_default=False,
        ),
    ]
